apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: katib-pytorch-tuning
  namespace: kubeflow
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
    metricStrategies:
    - name: accuracy
      value: max

  algorithm:
    algorithmName: random

  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.001"
        max: "0.1"
    - name: threshold
      parameterType: double
      feasibleSpace:
        min: "0.4"
        max: "0.9"

  trialTemplate:
    retain: true
    primaryContainerName: training-container
    trialParameters:
      - name: lr
        description: Learning rate
        reference: lr
      - name: threshold
        description: Threshold
        reference: threshold
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: ankitdockerhubprofile/katib-ff-whole:latest
                command:
                  - "python3"
                  - "/app/objective_fn.py"
                  - "--lr=${trialParameters.lr}"
                  - "--threshold=${trialParameters.threshold}"
                volumeMounts:
                  - name: log-volume
                    mountPath: /var/log/katib
            restartPolicy: Never
            volumes:
              - name: log-volume
                emptyDir: {}
  metricsCollectorSpec:
    collector:
      kind: File
    source:
      fileSystemPath:
        path: /var/log/katib/metrics.log
        kind: File
        format: JSON
